import { Stack, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { colors, spacing } from "@/constants/theme";
import { getStory, type Story } from "@/lib/api";

type StoryDetail = Story & { chapters?: Array<{ id: number; chapterNumber: number; title: string; body: string }> };

export default function StoryScreen() {
  const { slug } = useLocalSearchParams<{ slug: string }>(); const [story, setStory] = useState<StoryDetail>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  useEffect(() => { if (!slug) return; getStory(slug).then(setStory as (value: Story | undefined) => void).catch((err) => setError(err instanceof Error ? err.message : "Could not load story")).finally(() => setLoading(false)); }, [slug]);
  if (loading) return <ScreenContainer edges={["bottom", "left", "right"]}><View style={styles.center}><ActivityIndicator color={colors.primary} /></View></ScreenContainer>;
  if (!story) return <ScreenContainer edges={["bottom", "left", "right"]}><View style={styles.center}><Text style={styles.title}>{error ?? "Story unavailable"}</Text><Text style={styles.body}>Return to Discover and try another story.</Text></View></ScreenContainer>;
  return <><Stack.Screen options={{ title: story.title }} /><ScreenContainer edges={["bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><Image source={story.coverUrl ? { uri: story.coverUrl } : undefined} style={styles.cover} /><Text style={styles.category}>{story.category}</Text><Text style={styles.title}>{story.title}</Text><Text style={styles.author}>By {story.authorName}</Text><Text style={styles.body}>{story.description}</Text><View style={styles.divider} /><Text style={styles.section}>Chapters</Text>{story.chapters?.length ? story.chapters.map((chapter) => <View key={chapter.id} style={styles.chapter}><Text style={styles.chapterNumber}>CHAPTER {chapter.chapterNumber}</Text><Text style={styles.chapterTitle}>{chapter.title}</Text><Text numberOfLines={5} style={styles.chapterBody}>{chapter.body}</Text></View>) : <Text style={styles.body}>Chapters will appear here once this story is published.</Text>}</ScrollView></ScreenContainer></>;
}
const styles = StyleSheet.create({ content: { padding: spacing.lg, paddingBottom: 40 }, center: { alignItems: "center", flex: 1, justifyContent: "center", padding: spacing.lg }, cover: { alignSelf: "center", backgroundColor: colors.peach, borderRadius: 12, height: 300, marginBottom: 24, width: 210 }, category: { color: colors.primary, fontSize: 11, fontWeight: "700", letterSpacing: 2, textTransform: "uppercase" }, title: { color: colors.foreground, fontSize: 30, fontWeight: "700", lineHeight: 35, marginTop: 8 }, author: { color: colors.muted, fontSize: 14, marginTop: 6 }, body: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 18 }, divider: { backgroundColor: colors.border, height: 1, marginVertical: 28 }, section: { color: colors.foreground, fontSize: 22, fontWeight: "700", marginBottom: 12 }, chapter: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, marginBottom: 12, padding: 16 }, chapterNumber: { color: colors.primary, fontSize: 10, fontWeight: "700", letterSpacing: 1 }, chapterTitle: { color: colors.foreground, fontSize: 18, fontWeight: "700", marginTop: 6 }, chapterBody: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 8 } });
