ALTER TABLE `stories` ADD CONSTRAINT `stories_author_id_users_id_fk` FOREIGN KEY (`authorId`) REFERENCES `users`(`id`) ON DELETE SET NULL;
ALTER TABLE `storyChapters` ADD CONSTRAINT `story_chapters_story_id_stories_id_fk` FOREIGN KEY (`storyId`) REFERENCES `stories`(`id`) ON DELETE CASCADE;
ALTER TABLE `savedStories` ADD CONSTRAINT `saved_stories_user_id_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `savedStories` ADD CONSTRAINT `saved_stories_story_id_stories_id_fk` FOREIGN KEY (`storyId`) REFERENCES `stories`(`id`) ON DELETE CASCADE;
ALTER TABLE `reviews` ADD CONSTRAINT `reviews_user_id_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `reviews` ADD CONSTRAINT `reviews_story_id_stories_id_fk` FOREIGN KEY (`storyId`) REFERENCES `stories`(`id`) ON DELETE CASCADE;
ALTER TABLE `comments` ADD CONSTRAINT `comments_user_id_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `comments` ADD CONSTRAINT `comments_story_id_stories_id_fk` FOREIGN KEY (`storyId`) REFERENCES `stories`(`id`) ON DELETE CASCADE;
ALTER TABLE `readingProgress` ADD CONSTRAINT `reading_progress_user_id_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `readingProgress` ADD CONSTRAINT `reading_progress_story_id_stories_id_fk` FOREIGN KEY (`storyId`) REFERENCES `stories`(`id`) ON DELETE CASCADE;
ALTER TABLE `follows` ADD CONSTRAINT `follows_follower_id_users_id_fk` FOREIGN KEY (`followerId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `follows` ADD CONSTRAINT `follows_following_id_users_id_fk` FOREIGN KEY (`followingId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `journals` ADD CONSTRAINT `journals_author_id_users_id_fk` FOREIGN KEY (`authorId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `announcements` ADD CONSTRAINT `announcements_author_id_users_id_fk` FOREIGN KEY (`authorId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `notifications` ADD CONSTRAINT `notifications_recipient_id_users_id_fk` FOREIGN KEY (`recipientId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `notifications` ADD CONSTRAINT `notifications_actor_id_users_id_fk` FOREIGN KEY (`actorId`) REFERENCES `users`(`id`) ON DELETE SET NULL;
ALTER TABLE `reports` ADD CONSTRAINT `reports_reporter_id_users_id_fk` FOREIGN KEY (`reporterId`) REFERENCES `users`(`id`) ON DELETE CASCADE;
ALTER TABLE `stories` ADD INDEX `stories_status_category_date_idx` (`status`, `category`, `createdAt`);
ALTER TABLE `stories` ADD INDEX `stories_author_status_idx` (`authorId`, `status`);
ALTER TABLE `savedStories` ADD INDEX `saved_stories_user_created_idx` (`userId`, `createdAt`);
ALTER TABLE `reviews` ADD INDEX `reviews_story_status_date_idx` (`storyId`, `status`, `createdAt`);
ALTER TABLE `comments` DROP INDEX `comments_story_status_idx`, ADD INDEX `comments_story_status_idx` (`storyId`, `status`, `createdAt`);
ALTER TABLE `readingProgress` ADD INDEX `reading_progress_user_last_read_idx` (`userId`, `lastReadAt`);
ALTER TABLE `follows` ADD INDEX `follows_following_created_idx` (`followingId`, `createdAt`);
ALTER TABLE `journals` ADD INDEX `journals_author_status_date_idx` (`authorId`, `status`, `publishedAt`);
ALTER TABLE `announcements` ADD INDEX `announcements_author_status_date_idx` (`authorId`, `status`, `publishedAt`);
ALTER TABLE `notifications` DROP INDEX `notifications_recipient_read_idx`, ADD INDEX `notifications_recipient_read_idx` (`recipientId`, `readAt`, `createdAt`);
ALTER TABLE `reports` ADD INDEX `reports_status_created_idx` (`status`, `createdAt`), ADD INDEX `reports_target_idx` (`targetType`, `targetId`);
