import { int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), bio: text("bio"), location: varchar("location", { length: 160 }), website: varchar("website", { length: 240 }), profileVisibility: mysqlEnum("profileVisibility", ["public", "private"]).default("public").notNull(), emailNotifications: int("emailNotifications").default(1).notNull(), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export const stories = mysqlTable("stories", {
  id: int("id").autoincrement().primaryKey(), slug: varchar("slug", { length: 160 }).notNull().unique(), title: varchar("title", { length: 180 }).notNull(), subtitle: varchar("subtitle", { length: 220 }), description: text("description").notNull(), type: mysqlEnum("type", ["story", "article", "journal"]).default("story").notNull(), category: varchar("category", { length: 120 }).notNull(), coverUrl: text("coverUrl"), authorId: int("authorId"), authorName: varchar("authorName", { length: 180 }).notNull(), authorBio: text("authorBio"), status: mysqlEnum("status", ["draft", "pending", "published", "rejected"]).default("draft").notNull(), adminNote: text("adminNote"), rating: varchar("rating", { length: 8 }).default("0"), reviewCount: int("reviewCount").default(0).notNull(), estimatedMinutes: int("estimatedMinutes").default(5).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const storyChapters = mysqlTable("storyChapters", { id: int("id").autoincrement().primaryKey(), storyId: int("storyId").notNull(), chapterNumber: int("chapterNumber").notNull(), title: varchar("title", { length: 180 }).notNull(), body: text("body").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const savedStories = mysqlTable("savedStories", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), storyId: int("storyId").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const reviews = mysqlTable("reviews", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), storyId: int("storyId").notNull(), rating: int("rating").notNull(), body: text("body").notNull(), status: mysqlEnum("status", ["pending", "visible", "hidden", "flagged"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const comments = mysqlTable("comments", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), storyId: int("storyId").notNull(), body: text("body").notNull(), status: mysqlEnum("status", ["pending", "visible", "hidden"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const readingProgress = mysqlTable("readingProgress", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), storyId: int("storyId").notNull(), chapterNumber: int("chapterNumber").default(1).notNull(), progressPercent: int("progressPercent").default(0).notNull(), lastReadAt: timestamp("lastReadAt").defaultNow().onUpdateNow().notNull() });

export const follows = mysqlTable("follows", { id: int("id").autoincrement().primaryKey(), followerId: int("followerId").notNull(), followingId: int("followingId").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const journals = mysqlTable("journals", { id: int("id").autoincrement().primaryKey(), authorId: int("authorId").notNull(), slug: varchar("slug", { length: 180 }).notNull().unique(), title: varchar("title", { length: 220 }).notNull(), excerpt: text("excerpt").notNull(), body: text("body").notNull(), category: varchar("category", { length: 100 }), status: mysqlEnum("status", ["draft", "published"]).default("draft").notNull(), publishedAt: timestamp("publishedAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const announcements = mysqlTable("announcements", { id: int("id").autoincrement().primaryKey(), authorId: int("authorId").notNull(), body: text("body").notNull(), status: mysqlEnum("status", ["draft", "published"]).default("draft").notNull(), publishedAt: timestamp("publishedAt"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const notifications = mysqlTable("notifications", { id: int("id").autoincrement().primaryKey(), recipientId: int("recipientId").notNull(), actorId: int("actorId"), type: mysqlEnum("type", ["follow", "comment", "review", "new_book", "new_journal", "announcement", "admin"]).notNull(), referenceType: varchar("referenceType", { length: 60 }), referenceId: int("referenceId"), message: varchar("message", { length: 300 }).notNull(), readAt: timestamp("readAt"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const reports = mysqlTable("reports", { id: int("id").autoincrement().primaryKey(), reporterId: int("reporterId").notNull(), targetType: varchar("targetType", { length: 60 }).notNull(), targetId: int("targetId").notNull(), reason: mysqlEnum("reason", ["harassment", "spam", "inappropriate", "hate", "copyright", "other"]).notNull(), note: text("note"), status: mysqlEnum("status", ["open", "dismissed", "actioned"]).default("open").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Story = typeof stories.$inferSelect; export type InsertStory = typeof stories.$inferInsert; export type StoryChapter = typeof storyChapters.$inferSelect; export type Review = typeof reviews.$inferSelect; export type Journal = typeof journals.$inferSelect;
