import { Check, Eye, Loader2, Shield, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export default function AdminBooks() {
  const query = trpc.admin.pendingBooks.useQuery();
  const utils = trpc.useUtils();
  const moderate = trpc.admin.moderateBook.useMutation({ onSuccess: (_, input) => { void utils.admin.pendingBooks.invalidate(); toast.success(input.status === "published" ? "Book approved and published" : "Book rejected"); }, onError: (error) => toast.error(error.message) });
  if (query.isLoading) return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin" /> Loading submissions…</div>;
  if (query.error) return <div className="min-h-screen grid place-items-center p-6 text-center"><Shield size={30} /><p className="mt-3">You need administrator access to review submissions.</p></div>;
  return <main className="min-h-screen bg-background px-4 py-8 md:px-8"><div className="mx-auto max-w-6xl space-y-8"><header><p className="flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-muted-foreground"><Shield size={14} /> Editorial operations</p><h1 className="mt-3 text-4xl font-serif">Book submissions</h1><p className="mt-2 text-muted-foreground">Review writer submissions before they enter the public reading room.</p></header>{!query.data?.length ? <section className="rounded-2xl border bg-card p-10 text-center"><Check className="mx-auto" size={30} /><h2 className="mt-4 text-2xl font-serif">No pending submissions</h2><p className="mt-2 text-muted-foreground">New writer books will appear here after they are submitted.</p></section> : <div className="space-y-5">{query.data.map((book) => <article className="rounded-2xl border bg-card p-5 md:p-7" key={book.id}><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Pending review · {book.category}</p><h2 className="mt-2 text-3xl font-serif">{book.title}</h2><p className="mt-1 text-sm text-muted-foreground">By {book.authorName}{book.writer?.email ? ` · ${book.writer.email}` : ""}</p></div><div className="flex gap-2"><button className="button button-outline" disabled={moderate.isPending} onClick={() => moderate.mutate({ id: book.id, status: "rejected", note: "Please revise and resubmit this manuscript." })}><X size={15} /> Reject</button><button className="button button-primary" disabled={moderate.isPending} onClick={() => moderate.mutate({ id: book.id, status: "published" })}><Check size={15} /> Approve</button></div></div><p className="mt-5 max-w-3xl leading-7 text-muted-foreground">{book.description}</p><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-4"><p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">Chapters</p><p className="mt-2 text-2xl font-serif">{book.chapters.length}</p><div className="mt-3 space-y-2">{book.chapters.map((chapter) => <div className="flex items-center gap-2 text-sm" key={chapter.id}><Eye size={14} className="text-muted-foreground" /><span>{chapter.chapterNumber}. {chapter.title}</span></div>)}</div></div><div className="rounded-xl bg-slate-950 p-4 text-slate-100"><p className="text-xs uppercase tracking-[0.16em] text-amber-300">Review checklist</p><ul className="mt-3 space-y-2 text-sm text-slate-300"><li>• Title and synopsis present</li><li>• Author identity supplied</li><li>• At least one chapter supplied</li><li>• Human editorial decision required</li></ul></div></div></article>)}</div>}</div></main>;
}
