import { Check, Loader2, Shield, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export default function AdminModeration() {
  const query = trpc.admin.moderation.useQuery();
  const data = query.data as { comments: any[]; reviews: any[] } | undefined;
  const utils = trpc.useUtils();
  const comment = trpc.admin.moderateComment.useMutation({ onSuccess: () => { void utils.admin.moderation.invalidate(); toast.success("Comment decision saved"); } });
  const review = trpc.admin.moderateReview.useMutation({ onSuccess: () => { void utils.admin.moderation.invalidate(); toast.success("Review decision saved"); } });
  if (query.isLoading) return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin" /> Loading moderation queue…</div>;
  if (query.error) return <div className="min-h-screen grid place-items-center p-6 text-center"><Shield size={30} /><p className="mt-3">Administrator access is required.</p></div>;
  return <main className="min-h-screen bg-background px-4 py-8 md:px-8"><div className="mx-auto max-w-5xl space-y-8"><header><p className="flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-muted-foreground"><Shield size={14} /> Community safety</p><h1 className="mt-3 text-4xl font-serif">Review moderation</h1><p className="mt-2 text-muted-foreground">Approve thoughtful reader responses and keep unsafe content out of the public reading room.</p></header><section className="space-y-4"><h2 className="text-2xl font-serif">Pending comments</h2>{!data?.comments.length && <p className="rounded-xl border p-6 text-muted-foreground">No pending comments.</p>}{data?.comments.map((row) => <article className="rounded-xl border bg-card p-5" key={row.comment.id}><p className="text-sm text-muted-foreground">{row.user.name ?? "Reader"} · {new Date(row.comment.createdAt).toLocaleDateString()}</p><p className="mt-3 leading-7">{row.comment.body}</p><div className="mt-4 flex gap-2"><button className="button button-primary" onClick={() => comment.mutate({ id: row.comment.id, status: "visible" })}><Check size={15} /> Approve</button><button className="button button-outline" onClick={() => comment.mutate({ id: row.comment.id, status: "hidden" })}><X size={15} /> Hide</button></div></article>)}</section><section className="space-y-4"><h2 className="text-2xl font-serif">Pending reviews</h2>{!data?.reviews.length && <p className="rounded-xl border p-6 text-muted-foreground">No pending reviews.</p>}{data?.reviews.map((row) => <article className="rounded-xl border bg-card p-5" key={row.review.id}><p className="text-sm text-muted-foreground">{row.user.name ?? "Reader"} · {row.review.rating}/5 · {new Date(row.review.createdAt).toLocaleDateString()}</p><p className="mt-3 leading-7">{row.review.body}</p><div className="mt-4 flex gap-2"><button className="button button-primary" onClick={() => review.mutate({ id: row.review.id, status: "visible" })}><Check size={15} /> Approve</button><button className="button button-outline" onClick={() => review.mutate({ id: row.review.id, status: "hidden" })}><X size={15} /> Hide</button><button className="button button-outline" onClick={() => review.mutate({ id: row.review.id, status: "flagged" })}>Flag</button></div></article>)}</section></div></main>;
}
