import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, Check, Edit3, Feather, Globe2, Loader2, MapPin, Settings2, Trash2, Users } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { AppShell } from "./Home";

type ProfileTab = "overview" | "journals" | "settings";
export default function ProfilePage() {
  const { isAuthenticated, loading, logout } = useAuth();
  const profileQuery = trpc.profile.me.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const [tab, setTab] = useState<ProfileTab>("overview");
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ name: "", bio: "", location: "", website: "", profileVisibility: "public" as "public" | "private", emailNotifications: true });
  useEffect(() => { const profile = profileQuery.data?.user; if (!profile) return; setForm({ name: profile.name ?? "", bio: profile.bio ?? "", location: profile.location ?? "", website: profile.website ?? "", profileVisibility: profile.profileVisibility ?? "public", emailNotifications: Boolean(profile.emailNotifications) }); }, [profileQuery.data]);
  const update = trpc.profile.update.useMutation({ onSuccess: async () => { setEditing(false); toast("Profile updated", { icon: <Check size={15} /> }); await Promise.all([utils.profile.me.invalidate(), utils.auth.me.invalidate(), utils.community.profiles.invalidate()]); }, onError: (error) => toast(error.message || "Could not update profile") }); const deleteAccount = trpc.profile.deleteAccount.useMutation({ onSuccess: async (result) => { if (!result.success) { toast("Account deletion is temporarily unavailable"); return; } await logout(); window.location.href = "/"; }, onError: (error) => toast(error.message || "Could not delete your account") });
  if (loading || (isAuthenticated && profileQuery.isLoading)) return <AppShell><main className="container page-main profile-experience-loading"><Loader2 className="spin" size={22} /> Loading your profile...</main></AppShell>;
  if (!isAuthenticated) return <AppShell><main className="container page-main profile-gate"><Users size={30} /><p className="eyebrow eyebrow-coral">Your Blossom profile</p><h1>Your reading life, in one <em>place.</em></h1><p>Sign in to edit your profile, follow writers, and share your journals with the Blossom community.</p><button className="button button-primary" onClick={() => startLogin()}>Sign in to continue <ArrowRight size={16} /></button></main></AppShell>;
  const profile = profileQuery.data; if (!profile) return <AppShell><main className="container page-main profile-gate"><h1>Profile unavailable</h1><p>Please refresh and try again.</p></main></AppShell>;
  const user = profile.user; const initials = (user.name ?? "Blossom reader").split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const setField = <K extends keyof typeof form>(key: K, value: typeof form[K]) => setForm((current) => ({ ...current, [key]: value }));
  return <AppShell><main className="container page-main profile-experience"><section className="profile-hero-card"><div className="profile-avatar profile-avatar-large">{initials}</div><div className="profile-identity"><p className="eyebrow eyebrow-coral">Your Blossom profile</p><h1>{user.name ?? "Blossom reader"}</h1><p>{user.bio || "Reader · Story lover"}</p><div className="profile-meta">{user.location && <span><MapPin size={14} /> {user.location}</span>}{user.website && <a href={user.website.startsWith("http") ? user.website : `https://${user.website}`} target="_blank" rel="noreferrer"><Globe2 size={14} /> {user.website.replace(/^https?:\/\//, "")}</a>}</div></div><button className="button button-outline profile-edit-button" onClick={() => { setEditing((value) => !value); setTab("settings"); }}><Edit3 size={15} /> {editing ? "Close editor" : "Edit profile"}</button></section><section className="profile-counts"><div><strong>{profile.counts.followers}</strong><span>followers</span></div><div><strong>{profile.counts.following}</strong><span>following</span></div><div><strong>{profile.counts.journals}</strong><span>published journals</span></div></section><nav className="profile-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Overview</button><button className={tab === "journals" ? "active" : ""} onClick={() => setTab("journals")}>Authored journals <small>{profile.counts.journals}</small></button><button className={tab === "settings" ? "active" : ""} onClick={() => setTab("settings")}><Settings2 size={14} /> Settings</button></nav>{editing || tab === "settings" ? <ProfileSettings form={form} setField={setField} editing={editing} setEditing={setEditing} saving={update.isPending} deleting={deleteAccount.isPending} onSave={() => update.mutate(form)} onDelete={() => { if (window.confirm("Delete your Blossom account and all associated data? This cannot be undone.")) deleteAccount.mutate(); }} /> : tab === "journals" ? <JournalList journals={profile.journals} /> : <Overview profile={profile} />}</main></AppShell>;
}
function Overview({ profile }: { profile: NonNullable<ReturnType<typeof Object> & { user: unknown }> | any }) { const journals = profile.journals as Array<{ id: number; slug: string; title: string; excerpt: string; publishedAt: Date | string | null }>; return <div className="profile-overview"><section className="profile-panel profile-about-panel"><span className="mini-label">About you</span><p>{profile.user.bio || "Add a short bio so readers know what moves you to write."}</p><button className="text-button" onClick={() => undefined}>Your profile is {profile.user.profileVisibility === "private" ? "private" : "public"}</button></section><section className="profile-section"><div className="profile-section-heading"><div><span className="mini-label">Your writing</span><h2>Published journals</h2></div><Link href="/write" className="arrow-link">Open Writer Studio <ArrowRight size={15} /></Link></div>{journals.length ? <JournalList journals={journals.slice(0, 3)} /> : <div className="profile-empty"><Feather size={24} /><h3>Your first reflection is waiting.</h3><p>Write something honest and it will live here on your profile.</p><Link href="/write" className="button button-primary">Start writing <ArrowRight size={15} /></Link></div>}</section></div>; }
function JournalList({ journals }: { journals: Array<{ id: number; slug: string; title: string; excerpt: string; publishedAt: Date | string | null }> }) { return <section className="authored-journals">{journals.length === 0 ? <div className="profile-empty"><BookOpen size={24} /><h3>No published journals yet.</h3><p>Draft a reflection in Writer Studio, then publish it when it feels ready.</p><Link href="/write" className="button button-primary">Open Writer Studio <ArrowRight size={15} /></Link></div> : journals.map((journal) => <Link className="authored-journal-row" href={`/journal/${journal.slug}`} key={journal.id}><span className="journal-row-icon"><Feather size={17} /></span><span><span className="mini-label">Published {journal.publishedAt ? new Date(journal.publishedAt).toLocaleDateString(undefined, { month: "short", year: "numeric" }) : "recently"}</span><h3>{journal.title}</h3><p>{journal.excerpt}</p></span><ArrowRight size={16} /></Link>)}</section>; }
function ProfileSettings({ form, setField, editing, setEditing, saving, deleting, onSave, onDelete }: { form: { name: string; bio: string; location: string; website: string; profileVisibility: "public" | "private"; emailNotifications: boolean }; setField: <K extends keyof typeof form>(key: K, value: typeof form[K]) => void; editing: boolean; setEditing: (value: boolean) => void; saving: boolean; deleting: boolean; onSave: () => void; onDelete: () => void }) { return <section className="profile-settings"><div className="profile-section-heading"><div><span className="mini-label">Profile settings</span><h2>How readers meet you</h2></div><span className="settings-lock">Protected</span></div><div className="settings-card"><label>Name<input value={form.name} onChange={(event) => setField("name", event.target.value)} placeholder="Your display name" /></label><label>Bio<textarea value={form.bio} onChange={(event) => setField("bio", event.target.value)} rows={4} placeholder="A sentence or two about what you write and love." /></label><div className="settings-two-col"><label>Location<input value={form.location} onChange={(event) => setField("location", event.target.value)} placeholder="Lagos, Nigeria" /></label><label>Website<input value={form.website} onChange={(event) => setField("website", event.target.value)} placeholder="yourwebsite.com" /></label></div><div className="settings-choice"><div><strong>Profile visibility</strong><p>Choose whether readers can find your profile in the community.</p></div><select value={form.profileVisibility} onChange={(event) => setField("profileVisibility", event.target.value as "public" | "private")}><option value="public">Public</option><option value="private">Private</option></select></div><label className="settings-toggle"><input type="checkbox" checked={form.emailNotifications} onChange={(event) => setField("emailNotifications", event.target.checked)} /><span><strong>Community notifications</strong><small>Keep me updated about follows and new journals.</small></span></label><div className="settings-actions"><button className="button button-outline" onClick={() => setEditing(false)}>Cancel</button><button className="button button-primary" disabled={saving || !form.name.trim()} onClick={onSave}>{saving ? "Saving…" : editing ? "Save changes" : "Edit profile"} <Check size={15} /></button></div><div className="account-danger-zone"><div><strong>Delete account</strong><p>Delete your profile, saved stories, reading progress, community activity, and authored content. This cannot be undone.</p></div><button className="button button-danger" disabled={deleting} onClick={onDelete}><Trash2 size={15} />{deleting ? "Deleting…" : "Delete my account"}</button></div></div></section>; }
