import { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Link } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { colors, spacing } from "@/constants/theme";
import { listStories, type Story } from "@/lib/api";

export default function DiscoverScreen() {
  const [query, setQuery] = useState(""); const [stories, setStories] = useState<Story[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = setTimeout(() => { setLoading(true); listStories({ query: query.trim() || undefined, limit: 50 }).then(setStories).finally(() => setLoading(false)); }, 250); return () => clearTimeout(timer); }, [query]);
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><FlatList data={stories} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.content} ListHeaderComponent={<View><Text style={styles.kicker}>DISCOVER</Text><Text style={styles.title}>Find your next favorite.</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search stories, writers, themes" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.result}>{loading ? "Searching…" : `${stories.length} stories`}</Text></View>} ListEmptyComponent={loading ? <ActivityIndicator color={colors.primary} /> : <Text style={styles.empty}>No stories matched that search.</Text>} renderItem={({ item }) => <Link href={{ pathname: "/story/[slug]", params: { slug: item.slug } }} asChild><Pressable style={({ pressed }) => [styles.row, pressed && { opacity: .7 }]}><View style={styles.dot} /><View><Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.rowMeta}>{item.category} · {item.authorName}</Text></View></Pressable></Link>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: spacing.lg, paddingBottom: 36 }, kicker: { color: colors.primary, fontSize: 11, fontWeight: "700", letterSpacing: 2 }, title: { color: colors.foreground, fontSize: 30, fontWeight: "700", marginTop: 10 }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, color: colors.foreground, fontSize: 15, marginTop: 22, padding: 14 }, result: { color: colors.muted, fontSize: 12, marginBottom: 10, marginTop: 22 }, row: { alignItems: "center", borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: "row", gap: 14, paddingVertical: 17 }, dot: { backgroundColor: colors.peach, borderRadius: 22, height: 44, width: 44 }, rowTitle: { color: colors.foreground, fontSize: 16, fontWeight: "700" }, rowMeta: { color: colors.muted, fontSize: 12, marginTop: 4 }, empty: { color: colors.muted, paddingTop: 20 } });
