import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { createAnnouncement, createComment, createJournal, createReport, createReview, deleteAccount, getCommunityFeed, getMyProfile, getPublicAuthorProfile, getPublicJournal, getPublishedStoryBySlug, getReadingProgress, listModerationItems, listNotifications, listPendingBooks, listPublicProfiles, listPublishedStories, listReadingProgress, listSavedStories, listVisibleComments, listWriterBooks, listWriterDrafts, markNotificationsRead, moderateBook, moderateComment, moderateReview, previewWriterDraft, publishWriterDraft, saveReadingProgress, saveStoryForUser, saveWriterBook, saveWriterDraft, searchPublishedStories, submitWriterBook, toggleFollow, updateMyProfile, uploadBookCover } from "./db";

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query((opts) => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  stories: router({ list: publicProcedure.input(z.object({ category: z.string().trim().max(120).optional(), query: z.string().trim().max(120).optional(), limit: z.number().int().min(1).max(100).default(50), offset: z.number().int().min(0).max(100000).default(0) }).optional()).query(({ input }) => searchPublishedStories(input?.query, input?.category, input?.limit ?? 50, input?.offset ?? 0)), bySlug: publicProcedure.input(z.object({ slug: z.string().trim().min(1).max(180) })).query(({ input }) => getPublishedStoryBySlug(input.slug)), comments: publicProcedure.input(z.object({ storyId: z.number().int().positive() })).query(({ input }) => listVisibleComments(input.storyId)) }),
  reader: router({ library: protectedProcedure.query(({ ctx }) => listSavedStories(ctx.user.id)), progressList: protectedProcedure.query(({ ctx }) => listReadingProgress(ctx.user.id)), toggleSave: protectedProcedure.input(z.object({ storyId: z.number().int().positive() })).mutation(({ ctx, input }) => saveStoryForUser(ctx.user.id, input.storyId)), review: protectedProcedure.input(z.object({ storyId: z.number().int().positive(), rating: z.number().int().min(1).max(5), body: z.string().trim().min(2).max(2000) })).mutation(({ ctx, input }) => createReview(ctx.user.id, input.storyId, input.rating, input.body)), comment: protectedProcedure.input(z.object({ storyId: z.number().int().positive(), body: z.string().trim().min(2).max(2000) })).mutation(({ ctx, input }) => createComment(ctx.user.id, input.storyId, input.body)), progress: protectedProcedure.input(z.object({ storyId: z.number().int().positive() })).query(({ ctx, input }) => getReadingProgress(ctx.user.id, input.storyId)), saveProgress: protectedProcedure.input(z.object({ storyId: z.number().int().positive(), chapterNumber: z.number().int().positive(), progressPercent: z.number().int().min(0).max(100) })).mutation(({ ctx, input }) => saveReadingProgress(ctx.user.id, input.storyId, input.chapterNumber, input.progressPercent)) }),
  community: router({ profiles: publicProcedure.query(({ ctx }) => listPublicProfiles(ctx.user?.id)), author: publicProcedure.input(z.object({ id: z.number().int().positive() })).query(({ ctx, input }) => getPublicAuthorProfile(input.id, ctx.user?.id)), feed: publicProcedure.input(z.object({ mode: z.enum(["following", "discover"]) })).query(({ ctx, input }) => getCommunityFeed(ctx.user?.id, input.mode)), journalBySlug: publicProcedure.input(z.object({ slug: z.string().min(1) })).query(({ input }) => getPublicJournal(input.slug)), toggleFollow: protectedProcedure.input(z.object({ writerId: z.number().int().positive() })).mutation(({ ctx, input }) => toggleFollow(ctx.user.id, input.writerId)), createJournal: protectedProcedure.input(z.object({ title: z.string().trim().min(1).max(220), excerpt: z.string().trim().min(1).max(500), body: z.string().trim().min(1).max(10000), publish: z.boolean().default(false) })).mutation(({ ctx, input }) => createJournal(ctx.user.id, input.title, input.excerpt, input.body, input.publish)), createAnnouncement: protectedProcedure.input(z.object({ body: z.string().trim().min(1).max(2000), publish: z.boolean().default(false) })).mutation(({ ctx, input }) => createAnnouncement(ctx.user.id, input.body, input.publish)), notifications: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)), markNotificationsRead: protectedProcedure.mutation(({ ctx }) => markNotificationsRead(ctx.user.id)), report: protectedProcedure.input(z.object({ targetType: z.string().min(1), targetId: z.number().int().positive(), reason: z.enum(["harassment", "spam", "inappropriate", "hate", "copyright", "other"]), note: z.string().max(1000).optional() })).mutation(({ ctx, input }) => createReport(ctx.user.id, input.targetType, input.targetId, input.reason, input.note)) }),
  writer: router({ drafts: protectedProcedure.query(({ ctx }) => listWriterDrafts(ctx.user.id)), books: protectedProcedure.query(({ ctx }) => listWriterBooks(ctx.user.id)), saveBook: protectedProcedure.input(z.object({ id: z.number().int().positive().optional(), title: z.string().trim().min(1).max(180), subtitle: z.string().max(220).optional(), description: z.string().trim().min(1).max(5000), category: z.string().trim().min(1).max(120), authorName: z.string().trim().min(1).max(180), authorBio: z.string().max(2000).optional(), coverUrl: z.string().url().optional(), chapters: z.array(z.object({ title: z.string().trim().min(1).max(180), body: z.string().trim().min(1).max(30000) })).max(100) })).mutation(({ ctx, input }) => saveWriterBook(ctx.user.id, input)), submitBook: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => submitWriterBook(ctx.user.id, input.id)), saveDraft: protectedProcedure.input(z.object({ type: z.enum(["journal", "announcement"]), id: z.number().int().positive().optional(), title: z.string().max(220).optional(), excerpt: z.string().max(500).optional(), body: z.string().max(10000), category: z.string().max(100).optional() })).mutation(({ ctx, input }) => saveWriterDraft(ctx.user.id, input)), preview: protectedProcedure.input(z.object({ type: z.enum(["journal", "announcement"]), id: z.number().int().positive() })).query(({ ctx, input }) => previewWriterDraft(ctx.user.id, input.type, input.id)), publish: protectedProcedure.input(z.object({ type: z.enum(["journal", "announcement"]), id: z.number().int().positive() })).mutation(({ ctx, input }) => publishWriterDraft(ctx.user.id, input.type, input.id)) }),
  admin: router({ pendingBooks: adminProcedure.query(() => listPendingBooks()), moderateBook: adminProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["published", "rejected"]), note: z.string().max(2000).optional() })).mutation(({ input }) => moderateBook(input.id, input.status, input.note)), moderation: adminProcedure.query(() => listModerationItems()), moderateComment: adminProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["visible", "hidden"]) })).mutation(({ input }) => moderateComment(input.id, input.status)), moderateReview: adminProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["visible", "hidden", "flagged"]) })).mutation(({ input }) => moderateReview(input.id, input.status)) }),
  uploads: router({ cover: protectedProcedure.input(z.object({ filename: z.string().min(1).max(180), contentType: z.string(), base64: z.string().min(1) })).mutation(({ ctx, input }) => uploadBookCover(ctx.user.id, input.filename, input.contentType, input.base64)) }),
  profile: router({ me: protectedProcedure.query(({ ctx }) => getMyProfile(ctx.user.id)), update: protectedProcedure.input(z.object({ name: z.string().trim().min(1).max(120), bio: z.string().max(1000), location: z.string().max(160), website: z.string().max(240), profileVisibility: z.enum(["public", "private"]), emailNotifications: z.boolean() })).mutation(({ ctx, input }) => updateMyProfile(ctx.user.id, input)), deleteAccount: protectedProcedure.mutation(async ({ ctx }) => { const result = await deleteAccount(ctx.user.id); if (result.success) ctx.res.clearCookie(COOKIE_NAME, { ...getSessionCookieOptions(ctx.req), maxAge: -1 }); return result; }) }),
});
export type AppRouter = typeof appRouter;
