import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { createAnnouncement, createJournal, createReport, createReview, getCommunityFeed, getMyProfile, getPublicJournal, getPublishedStoryBySlug, listNotifications, listPublicProfiles, listPublishedStories, listWriterDrafts, previewWriterDraft, publishWriterDraft, saveStoryForUser, saveWriterDraft, toggleFollow, updateMyProfile } from "./db";

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query((opts) => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  stories: router({ list: publicProcedure.input(z.object({ category: z.string().optional() }).optional()).query(({ input }) => listPublishedStories(input?.category)), bySlug: publicProcedure.input(z.object({ slug: z.string().min(1) })).query(({ input }) => getPublishedStoryBySlug(input.slug)) }),
  reader: router({ toggleSave: protectedProcedure.input(z.object({ storyId: z.number().int().positive() })).mutation(({ ctx, input }) => saveStoryForUser(ctx.user.id, input.storyId)), review: protectedProcedure.input(z.object({ storyId: z.number().int().positive(), rating: z.number().int().min(1).max(5), body: z.string().trim().min(2).max(2000) })).mutation(({ ctx, input }) => createReview(ctx.user.id, input.storyId, input.rating, input.body)) }),
  community: router({ profiles: publicProcedure.query(({ ctx }) => listPublicProfiles(ctx.user?.id)), feed: publicProcedure.input(z.object({ mode: z.enum(["following", "discover"]) })).query(({ ctx, input }) => getCommunityFeed(ctx.user?.id, input.mode)), journalBySlug: publicProcedure.input(z.object({ slug: z.string().min(1) })).query(({ input }) => getPublicJournal(input.slug)), toggleFollow: protectedProcedure.input(z.object({ writerId: z.number().int().positive() })).mutation(({ ctx, input }) => toggleFollow(ctx.user.id, input.writerId)), createJournal: protectedProcedure.input(z.object({ title: z.string().trim().min(1).max(220), excerpt: z.string().trim().min(1).max(500), body: z.string().trim().min(1).max(10000), publish: z.boolean().default(false) })).mutation(({ ctx, input }) => createJournal(ctx.user.id, input.title, input.excerpt, input.body, input.publish)), createAnnouncement: protectedProcedure.input(z.object({ body: z.string().trim().min(1).max(2000), publish: z.boolean().default(false) })).mutation(({ ctx, input }) => createAnnouncement(ctx.user.id, input.body, input.publish)), notifications: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)), report: protectedProcedure.input(z.object({ targetType: z.string().min(1), targetId: z.number().int().positive(), reason: z.enum(["harassment", "spam", "inappropriate", "hate", "copyright", "other"]), note: z.string().max(1000).optional() })).mutation(({ ctx, input }) => createReport(ctx.user.id, input.targetType, input.targetId, input.reason, input.note)) }),
  writer: router({ drafts: protectedProcedure.query(({ ctx }) => listWriterDrafts(ctx.user.id)), saveDraft: protectedProcedure.input(z.object({ type: z.enum(["journal", "announcement"]), id: z.number().int().positive().optional(), title: z.string().max(220).optional(), excerpt: z.string().max(500).optional(), body: z.string().max(10000), category: z.string().max(100).optional() })).mutation(({ ctx, input }) => saveWriterDraft(ctx.user.id, input)), preview: protectedProcedure.input(z.object({ type: z.enum(["journal", "announcement"]), id: z.number().int().positive() })).query(({ ctx, input }) => previewWriterDraft(ctx.user.id, input.type, input.id)), publish: protectedProcedure.input(z.object({ type: z.enum(["journal", "announcement"]), id: z.number().int().positive() })).mutation(({ ctx, input }) => publishWriterDraft(ctx.user.id, input.type, input.id)) }),
  profile: router({ me: protectedProcedure.query(({ ctx }) => getMyProfile(ctx.user.id)), update: protectedProcedure.input(z.object({ name: z.string().trim().min(1).max(120), bio: z.string().max(1000), location: z.string().max(160), website: z.string().max(240), profileVisibility: z.enum(["public", "private"]), emailNotifications: z.boolean() })).mutation(({ ctx, input }) => updateMyProfile(ctx.user.id, input)) }),
});
export type AppRouter = typeof appRouter;
